[project]
name = "pickpcparts"
version = "0.1.0"
description = "Clone of PCPartPicker—the popular computer component comparison website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
    "django-settings-env>=5.5.0",
    "psycopg[binary]>=3.2.9",
]
