# Generated by Django 5.2.1 on 2025-05-20 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('rpm', models.PositiveIntegerField()),
                ('noise_level', models.PositiveIntegerField()),
                ('pwm', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseFormFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('memory', models.PositiveIntegerField()),
                ('core_clock', models.PositiveIntegerField()),
                ('boost_clock', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('speed', models.PositiveIntegerField()),
                ('modules', models.PositiveIntegerField()),
                ('first_word_latency', models.PositiveIntegerField()),
                ('cas_latency', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessorCooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('rpm', models.PositiveIntegerField()),
                ('noise_level', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StorageFormFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StorageInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('external_volume', models.PositiveIntegerField()),
                ('formfactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caseformfactor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('core_count', models.PositiveIntegerField()),
                ('core_clock', models.PositiveIntegerField()),
                ('boost_clock', models.PositiveIntegerField()),
                ('tdp', models.PositiveIntegerField()),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('max_memory', models.PositiveIntegerField()),
                ('memory_slots', models.PositiveIntegerField()),
                ('formfactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caseformfactor')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('wattage', models.PositiveIntegerField()),
                ('efficiency', models.CharField(choices=[(0, 'None'), (1, 'Plus'), (2, 'Bronze'), (3, 'Silver'), (4, 'Gold'), (5, 'Platinum'), (6, 'Titanium')], max_length=1)),
                ('modularity', models.CharField(choices=[(0, 'None'), (1, 'Semi'), (2, 'Full')], max_length=1)),
                ('formfactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.storageformfactor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('cache', models.PositiveIntegerField()),
                ('form_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.storageformfactor')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.storageinterface')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
