# Generated by Django 5.2.1 on 2025-05-21 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='case',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='case_fans',
            field=models.ManyToManyField(blank=True, to='app.casefan'),
        ),
        migrations.AddField(
            model_name='build',
            name='graphics_card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.graphicscard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='memory',
            field=models.ManyToManyField(to='app.memory'),
        ),
        migrations.AddField(
            model_name='build',
            name='motherboard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.motherboard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='power_supply',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.powersupply'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='processor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.processor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='processor_cooler',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.processorcooler'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='storage',
            field=models.ManyToManyField(to='app.storage'),
        ),
    ]
