# Generated by Django 5.2.1 on 2025-05-21 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_build_date_created_build_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer'),
        ),
        migrations.AlterField(
            model_name='casefan',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer'),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer'),
        ),
        migrations.AlterField(
            model_name='processorcooler',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer'),
        ),
    ]
