# Generated by Django 5.2.1 on 2025-05-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_manufacturer_alter_case_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorcooler',
            name='socket',
            field=models.ManyToManyField(to='app.socket'),
        ),
    ]
