# Generated by Django 5.2.1 on 2025-05-21 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_processorcooler_socket'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='memory',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.memorytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboard',
            name='supported_memory',
            field=models.ManyToManyField(to='app.memorytype'),
        ),
    ]
