# Generated by Django 5.2.1 on 2025-05-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_memorytype_memory_type_motherboard_supported_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='capacity_per_module',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
