# Generated by Django 5.2.1 on 2025-05-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_powersupply_formfactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupply',
            name='efficiency',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Plus'), (2, 'Bronze'), (3, 'Silver'), (4, 'Gold'), (5, 'Platinum'), (6, 'Titanium')]),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='modularity',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Semi'), (2, 'Full')]),
        ),
    ]
